### PR TITLE
Fix telemetry modal

### LINKED ISSUE #99: Telemetry modal doesn't appear
### Expected Behavior

The first time Scratch Desktop runs, a dialog should appear asking the user to opt in or opt out of telemetry.

### Actual Behavior

The dialog never appears and the opt-in state remains undefined. On the plus side, Scratch Desktop does not transmit telemetry in this state.

### Steps to Reproduce

1. If you have run Scratch Desktop before, remove its internal settings & cache directory:
   - On Windows, this is `%APPDATA%\Scratch Desktop\`
   - On macOS, this is either `~/Library/Application Support/Scratch Desktop/` or `~/Library/Containers/edu.mit.scratch.scratch-desktop/Data/Library/Application Support/Scratch Desktop/`; I recommend deleting both.
   - For unpackaged development builds, replace "Scratch Desktop" with "Electron"
   - In theory you should be able to just delete `telemetry.json` from the directory but deleting the whole directory is fine too.
2. Run Scratch Desktop and wait for it to fully load.
3. You should see something like the image below.
   - If the telemetry dialog is missing even after deleting the settings listed in step 1, you are seeing this issue.

image

### Operating System and Browser

This affects both macOS and Windows, store and direct-download.

### LINKED ISSUE #102: Telemetry cache reset instructions should be in README
The instructions for how to develop the telemetry functionality should be in the README. This includes cache reset instructions as here: https://github.com/LLK/scratch-desktop/issues/99#issue-557663998

### PR DESCRIPTION
**Pull request by cwillisf**
### Resolves

Resolves #99 (again)
Resolves #102

### Proposed Changes

This change splits `ScratchDesktopHOC` / `ScratchDesktopComponent` into `ScratchDesktopOuterHOC` / `ScratchDesktopOuterComponent` and `ScratchDesktopInnerHOC` / `ScratchDesktopInnerComponent`.

`ScratchDesktopOuterComponent` is now responsible for `showTelemetryModal` which only works if it comes from outside the `AppStateHOC` since it's used in the `AppStateHOC` constructor. The outer component also handles a few static props, like `isScratchDesktop`.

`ScratchDesktopInnerComponent` handles everything else, most notably anything that interacts with the state established by `AppStateHOC`.

I've also added telemetry reset instructions to `README.md` as suggested in #102.

### Reason for Changes

The order of HOC composition -- specifically, `AppStateHOC` vs. `ScratchDesktopHOC` -- has gone back and forth a few times in the process of fixing issues. It turns out this is because neither order was correct: some properties that `ScratchDesktopHOC` supplies are needed by `AppStateHOC`, but some properties of `ScratchDesktopHOC` require state information that's provided by `AppStateHOC`.

This change splits those two categories into two separate HOCs, resolving that conflict.

### Test Coverage

- Tested that this doesn't break #150: Starting the app with a project file name on the command line still opens the project
- Tested that this fixes #99 by deleting `telemetry.json` and confirming that the telemetry modal does appear

### CODE REVIEW

**Comment by cwillisf** [comment]
I ran into this while working on https://github.com/cwillisf/scratch-desktop/tree/privacy-policy which is almost ready for review...

File: src/renderer/app.jsx [hunk 1]
```diff
@@ -43,8 +43,26 @@ document.body.appendChild(appTarget);
...
-const ScratchDesktopHOC = function (WrappedComponent) {
-    class ScratchDesktopComponent extends React.Component {
+const ScratchDesktopOuterHOC = function (WrappedComponent) {
+    const ScratchDesktopOuterComponent = function (props) {
+        const shouldShowTelemetryModal = (typeof ipcRenderer.sendSync('getTelemetryDidOptIn') !== 'boolean');
+
+        return (<WrappedComponent
+            canEditTitle
+            canModifyCloudData={false}
+            isScratchDesktop
```
Comment (rschamp) [inline src/renderer/app.jsx]: These 3 props seem like they belong in the inner HOC since one could see the role of this outer HOC as to pass props into `AppStateHOC`. If that's the case then I think it would be clearer if we only had things necessary for AppStateHOC in this outer HOC, maybe accompanied by a more specific name like `ScratchDesktopAppStateHOC`?

**Review by rschamp — CHANGES_REQUESTED** [review]

**Review by rschamp — APPROVED** [review]
