### PR TITLE
Show main window ASAP, even if it's just a loading screen

### LINKED ISSUE #59: Scratch Desktop can take a long time to appear after launch
Expected behavior: Scratch Desktop should display a splash screen or loading screen ASAP after launch

Actual behavior: Depending on the computer it can take more than 20 seconds for the Scratch Desktop window to appear. Even on a relatively fast computer it can take more than 5 seconds. This can lead the user to believe something has gone wrong, and they may attempt to launch the application multiple times.

### PR DESCRIPTION
**Pull request by cwillisf**
Resolves #59 

There are two parts to this change:
- Make a new, tiny stub JS file which does nothing but load the "real" JS asynchronously. This by itself allows the main window to appear quickly, though it's just an empty white window.
- Override the render process `index.html` with one which contains a loading message. This causes the empty to instead display that loading message until the GUI's loading screen takes over.

The `app.js` here is `index.js` renamed with no changes.

Marking this as a draft PR since the current loading screen is a temporary placeholder ;)

CC @paulkaplan - this kind of approach may also be interesting for other platforms...

CC @carljbowman - we should talk about what the loading screen should look like

### CODE REVIEW

File: src/renderer/app.js [hunk 1]
```diff
@@ -0,0 +1,49 @@
+import {ipcRenderer, shell} from 'electron';
```
Comment (cwillisf) [inline src/renderer/app.js]: Note that the contents of this file, `app.js`, are identical to the old `index.js`. Only the name has changed to ~protect~ help with loading the file asynchronously.
